---
- name: Installing Zabbix agent
  hosts: 
    - dhcp
    - hpc-gateway 

  tasks:

  - name: Install Zabbix repo
    yum:
      name: "https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-1.el7.noarch.rpm"
      state: present
    become: true
    

  - name: Install Zabbix agent
    yum:
        name: zabbix-agent
        state: present
    become: true


  - name: Zabbix agent server in conf
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: Server=10.10.100.250
    become: true
    tags:
      - zabbix
      - zabbix-conf


  - name: Enable and start Zabbix agent service
    systemd:
      name: zabbix-agent
      state: started
      enabled: yes
    become: true
  
